### ISSUE TITLE
Assinmenrt 1 Problem 1: Factorial Calculator

### ISSUE THREAD

**Issue by 55bit23** [vtcbca/basic-programming-54bit23#2]
Can someone explain this

**Comment by 62bit23** [comment]
A factorial is just the result of multiplying a number by all the smaller numbers down to 1.

**Comment by 55bit23** [comment]
Wich datatype i can use to store it

**Comment by 62bit23** [comment]
Integer **(int)**

**Comment by 55bit23** [comment]
Ok i will use int datatype in my python program .

**Comment by 62bit23** [comment]
if you are counting a factorial of big number than you must use **long int**

**Comment by 55bit23** [comment]
Why is the factorial of negative numbers undefined?

**Comment by 62bit23** [comment]
The factorial of a number is only defined for positive numbers (like 1, 2, 3, and so on) and 0.

**Comment by 55bit23** [comment]
What is the factorial of 1?

**Comment by 62bit23** [comment]
the factorial of 1 is just 1 because there’s only one number to multiply (which is 1 itself).

**Comment by 55bit23** [comment]
OK thank  you for solving my problem
