### ISSUE TITLE
Assignment-2:  Prime Number

### ISSUE THREAD

**Issue by 54bit23** [vtcbca/basic-programming-54bit23#4]
can some one tell me what is prime number?

**Comment by 54bit23** [comment]
A number greater than 1 that has only two divisors: 1 and itself

**Comment by 50bit23** [comment]
A number greater than 1 that has only two divisors: 1 and itself

**Comment by 54bit23** [comment]
How do you check if a number is prime in Python?

**Comment by 50bit23** [comment]
By dividing it by all numbers from 2 to 𝑛 and checking if it has no divisors.

**Comment by 54bit23** [comment]
Why is 2 a special prime number?

**Comment by 50bit23** [comment]
It is the smallest prime and the only even prime number.

**Comment by 54bit23** [comment]
Can negative numbers be prime?

**Comment by 50bit23** [comment]
No, prime numbers are positive integers greater than 1

**Comment by 54bit23** [comment]
How would you modify the program to find all primes up to 50?

**Comment by 50bit23** [comment]
Use a loop to check each number up to 50 and store primes in a list.

**Comment by 54bit23** [comment]
ok got it @50bit23
