### ISSUE TITLE
Assignment-3 : Fibonacci Sequence Generator

### ISSUE THREAD

**Issue by 62bit23** [vtcbca/basic-programming-54bit23#5]
Can someone tell me what is Fibonacci sequence?

**Comment by 54bit23** [comment]
he Fibonacci sequence is a series of numbers where each number is the sum of the two preceding ones, starting from 0 and 1. For example: 0, 1, 1, 2, 3, 5, 8, ....

**Comment by 62bit23** [comment]
Can the Fibonacci sequence start with numbers other than 0 and 1?

**Comment by 54bit23** [comment]
Yes, you can define a custom starting point, but the classic sequence begins with 0 and 1.

**Comment by 54bit23** [comment]
How can you generate the Fibonacci sequence up to a specific number (e.g., up to 50)?

**Comment by 62bit23** [comment]
How can you generate the Fibonacci sequence up to a specific number (e.g., up to 50)?

**Comment by 54bit23** [comment]
Use a loop and stop when the next term exceeds the target number.

**Comment by 62bit23** [comment]
Wich datatype i can use in my python prgram ?

**Comment by 54bit23** [comment]
In your Python program, you can use the following data types:

1. **int**: To store Fibonacci numbers (e.g., `0, 1, 2, 3`).  
2. **list**: To store the sequence as a collection of numbers.  
3. **float**: If working with Fibonacci numbers that involve division or approximations.  
4. **bool**: For conditions or flags in the program.  
5. **str**: To format or display the sequence as text.

**Comment by 62bit23** [comment]
what is diffrence between in , int and float?

**Comment by 54bit23** [comment]
int: A data type for whole numbers (e.g., 5).
float: A data type for numbers with decimals (e.g., 5.5).

**Comment by 62bit23** [comment]
OK thanks.
